_BASE_: "./yolov5_base.yaml"
DETECTOR:
  WEIGHT: "/model_zoo/detection/of_yolo_ckpt/yolov5m_ckpt"
  BACKBONE:
    DEPTH: 49
    WIDTH_PER_GROUP: 48
    STEM_OUT_CHANNELS: 48
    DARK2_OUT_CHANNELS: 96
  FPN:
    BOTTLENECK_CHANNELS: [384, 192, 192, 384]
    OUT_CHANNELS: [384, 192, 384, 768]
    LATERAL_NUM_BLOCKS: [2, 2, 2, 2]
