ENV:
  NUM_GPUS: 1
DTYPE: "float32"
DETECTOR:
  TYPE: "YOLOv5"
  BACKBONE:
    TYPE: "CSPDarkNet"
    DEPTH: 65
    FREEZE_STAGE: 2
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
    NUM_GROUPS: 1
    WIDTH_PER_GROUP: 64
    STEM_OUT_CHANNELS: 64
    DARK2_OUT_CHANNELS: 128
    WEIGHT_DECAY: 0.0005
  FPN:
    TYPE: "YOLOv5FPN"
    IN_FEATURES: ["dark3", "dark4", "dark5"]
    OUT_FEATURES: ["p3", "p4", "p5"]
    START_IN_CHANNELS: 512
    BOTTLENECK_CHANNELS: [512, 256, 256, 512]
    OUT_CHANNELS: [512, 256, 512, 1024]
    LATERAL_NUM_BLOCKS: [3, 3, 3, 3]
    WEIGHT_DECAY: 0.0005
  DENSE_HEAD:
    TYPE: "YOLOv3Head"
    IN_FEATURES: ["p3", "p4", "p5"]
    NUM_CLASSES: 80
    PRE_NMS_TOPK: 30000
    SCORE_THRESH: 0.001
    NMS_THRESH: 0.65
    DETECTIONS_PER_IMG: 300
    WEIGHT_DECAY: 0.0005
    ANCHOR_GENERATOR:
      TYPE: "YoloAnchorGenerator"
      SIZES: [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]]
      STRIDES: [8, 16, 32]
DATASETS:
  TEST: "/dataset/mscoco_2017"
  IMAGE_DIR_TEST: "val2017"
  ANNOTATION_TEST: "annotations/instances_val2017.json"
INPUT:
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
  COLOR_SPACE: "RGB"
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "./output"
