_BASE_: "./yolov5_base.yaml"
DETECTOR:
  WEIGHT: "/model_zoo/detection/of_yolo_ckpt/yolov5x_ckpt"
  BACKBONE:
    DEPTH: 81
    WIDTH_PER_GROUP: 80
    STEM_OUT_CHANNELS: 80
    DARK2_OUT_CHANNELS: 160
  FPN:
    BOTTLENECK_CHANNELS: [640, 320, 320, 640]
    OUT_CHANNELS: [640, 320, 640, 1280]
    LATERAL_NUM_BLOCKS: [4, 4, 4, 4]
