ENV:
  NUM_GPUS: 1
DTYPE: "float32"
DETECTOR:
  TYPE: "MaskRCNN"
  BACKBONE:
    TYPE: "ResNet"
    DEPTH: 50
    FREEZE_STAGE: 2
    OUT_FEATURES: ["res4"]
    NUM_GROUPS: 1
    WIDTH_PER_GROUP: 64
    STEM_OUT_CHANNELS: 64
    RES2_OUT_CHANNELS: 256
    STRIDE_IN_1X1: True
    WEIGHT_DECAY: 0.0005
  RPN_HEAD:
    TYPE: "RPNHead"
    IN_CHANNELS: 1024
    IN_FEATURES: ["res4"]
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 12000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.7
    MIN_SIZE: 0.0
    BOUNDARY_THRESH: 0.0
    FG_IOU_THRESHOLD: 0.7
    BG_IOU_THRESHOLD: 0.3
    WEIGHT_DECAY: 0.0005
    ANCHOR_GENERATOR:
      TYPE: "AnchorGenerator"
      SIZES: [[32, 64, 128, 256, 512]]
      ASPECT_RATIOS: [0.5, 1.0, 2.0]
      STRIDES: [16]
  ROI_HEAD:
    TYPE: "StandardRoIHead"
    IN_FEATURES: ["res4"]
    NUM_CLASSES: 81
    NMS_THRESH: 0.5
    SCORE_THRESH: 0.05
    DETECTIONS_PER_IMG: 100
    SHARED_HEAD:
      TYPE: "ResLayer"
      DEPTH: 50
      STAGE: 3
      NUM_GROUPS: 1
      WIDTH_PER_GROUP: 64
      RES2_OUT_CHANNELS: 256
      STRIDE_IN_1X1: True
      WEIGHT_DECAY: 0.0005
    BOX_HEAD:
      TYPE: "ConvFCBoxHead"
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_SCALES: (0.0625,)
      NUM_CONV: 0
      CONV_DIM: 256
      NUM_FC: 0
      FC_DIM: 1024
      NUM_CLASSES: 81
      WITH_AVG_POOL: True
      WEIGHT_DECAY: 0.0005
    MASK_HEAD:
      TYPE: "FCNMaskHead"
      IN_CHANNELS: 2048
      OUT_CHANNELS: 256
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_SCALES: (0.0625,)
      NUM_CONV: 0
      CONV_DIM: 256
      NUM_CLASSES: 81
      WEIGHT_DECAY: 0.0005
DATASETS:
  TEST: "/dataset/mscoco_2017"
  IMAGE_DIR_TEST: "val2017"
  ANNOTATION_TEST: "annotations/instances_val2017.json"
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./output"
