_BASE_: "./fcos_R_50_FPN.yaml"
DETECTOR:
  WEIGHT: "/model_zoo/detection/of_d2_ckpt/fcos_ms_X_101_64x4d_FPN_2x_d2_ckpt"
  BACKBONE:
    STRIDE_IN_1X1: False
    DEPTH: 101
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
INPUT:
  PIXEL_STD: [1.0, 1.0, 1.0]
