ENV:
  NUM_GPUS: 1
DTYPE: "float32"
DETECTOR:
  TYPE: "YOLOv3"
  BACKBONE:
    TYPE: "DarkNet"
    DEPTH: 13
    FREEZE_STAGE: 2
    OUT_FEATURES: ["dark5", "dark6"]
    NUM_GROUPS: 1
    WIDTH_PER_GROUP: 32
    STEM_OUT_CHANNELS: 16
    DARK2_OUT_CHANNELS: 32
    WEIGHT_DECAY: 0.0005
  FPN:
    TYPE: "YOLOv3FPN"
    IN_FEATURES: ["dark5", "dark6"]
    OUT_FEATURES: ["p5", "p6"]
    START_IN_CHANNELS: 512
    OUT_CHANNELS: [256, 512]
    LATERAL_NUM_BLOCKS: [0, 0]
    INPUT_CONV: True
    WEIGHT_DECAY: 0.0005
  DENSE_HEAD:
    TYPE: "YOLOv3Head"
    IN_FEATURES: ["p5", "p6"]
    NUM_CLASSES: 80
    PRE_NMS_TOPK: 30000
    SCORE_THRESH: 0.001
    NMS_THRESH: 0.65
    DETECTIONS_PER_IMG: 300
    WEIGHT_DECAY: 0.0005
    ANCHOR_GENERATOR:
      TYPE: "YoloAnchorGenerator"
      SIZES: [[10, 14, 23, 27, 37, 58], [81, 82, 135, 169, 344, 319]]
      STRIDES: [16, 32]
DATASETS:
  TEST: "/dataset/mscoco_2017"
  IMAGE_DIR_TEST: "val2017"
  ANNOTATION_TEST: "annotations/instances_val2017.json"
INPUT:
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
  COLOR_SPACE: "RGB"
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "./output"
