_BASE_: "./yolov3_base.yaml"
DETECTOR:
  WEIGHT: "/model_zoo/detection/of_yolo_ckpt/yolov3_ckpt"
  BACKBONE:
    DEPTH: 53
    OUT_FEATURES: ["dark4", "dark5", "dark6"]
    STEM_OUT_CHANNELS: 32
    DARK2_OUT_CHANNELS: 64
  FPN:
    IN_FEATURES: ["dark4", "dark5", "dark6"]
    OUT_FEATURES: ["p4", "p5", "p6"]
    OUT_CHANNELS: [256, 512, 1024]
    LATERAL_NUM_BLOCKS: [2, 2, 2]
    INPUT_CONV: False
  DENSE_HEAD:
    IN_FEATURES: ["p4", "p5", "p6"]
    ANCHOR_GENERATOR:
      TYPE: "YoloAnchorGenerator"
      SIZES: [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]]
      STRIDES: [8, 16, 32]
