ENV:
  NUM_GPUS: 1
DTYPE: "float32"
DETECTOR:
  TYPE: "HybridTaskCascade"
  BACKBONE:
    TYPE: "ResNet"
    DEPTH: 50
    FREEZE_STAGE: 2
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NUM_GROUPS: 1
    WIDTH_PER_GROUP: 64
    STEM_OUT_CHANNELS: 64
    RES2_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    WEIGHT_DECAY: 0.0005
  FPN:
    TYPE: "FPN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    START_IN_CHANNELS: 256
    OUT_CHANNELS: [256, 256, 256, 256]
    WEIGHT_DECAY: 0.0005
    TOP_BLOCK:
      TYPE: "LastLevelMaxPool"
  RPN_HEAD:
    TYPE: "RPNHead"
    IN_CHANNELS: 256
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.7
    MIN_SIZE: 0.0
    BOUNDARY_THRESH: 0.0
    FG_IOU_THRESHOLD: 0.7
    BG_IOU_THRESHOLD: 0.3
    WEIGHT_DECAY: 0.0005
    ANCHOR_GENERATOR:
      TYPE: "AnchorGenerator"
      SIZES: [[32], [64], [128], [256], [512]]
      ASPECT_RATIOS: [0.5, 1.0, 2.0]
      STRIDES: [4, 8, 16, 32, 64]
  ROI_HEAD:
    TYPE: "HybridTaskCascadeRoIHead"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 81
    NMS_THRESH: 0.5
    SCORE_THRESH: 0.001
    DETECTIONS_PER_IMG: 100
    BBOX_REG_WEIGHTS: ((10.0, 10.0, 5.0, 5.0), (20.0, 20.0, 10.0, 10.0), (30.0, 30.0, 15.0, 15.0))
    BOX_HEAD:
      TYPE: "ConvFCBoxHead"
      POOLER_RESOLUTION: 7
      POOLER_SAMPLING_RATIO: 0
      POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
      NUM_CONV: 0
      CONV_DIM: 256
      NUM_FC: 2
      FC_DIM: 1024
      NUM_CLASSES: 81
      CLS_AGNOSTIC_BBOX_REG: True
      WEIGHT_DECAY: 0.0005
    MASK_HEAD:
      TYPE: "HTCMaskHead"
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
      WITH_CONV_RES: [False, True, True]
      NUM_CONV: 4
      CONV_DIM: 256
      NUM_CLASSES: 81
      WEIGHT_DECAY: 0.0005
    SEMANTIC_HEAD:
      TYPE: "FusedSemanticHead"
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      POOLER_SCALES: (0.125,)
      IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
      FUSION_LEVEL: "p3"
      FUSE_CONV_DIM: 256
      NUM_CONV: 4
      CONV_DIM: 256
      NUM_CLASSES: 183
      WEIGHT_DECAY: 0.0005
ENV:
  CUDNN_BUFFER_SIZE_LIMIT: 1536
DATASETS:
  TEST: "/dataset/mscoco_2017"
  IMAGE_DIR_TEST: "val2017"
  ANNOTATION_TEST: "annotations/instances_val2017.json"
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  COLOR_SPACE: "RGB"
  SIZE_DIVISIBILITY: 64
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "./output"
